apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core
  annotations:
    description: AntiNex - AI Core - Celery Worker for Training and Making Predictions
    runtime: python3
  labels:
    app: core
    purpose: worker
    layer: backend
    ai.framework: keras
    ai.backend: tensorflow
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
        purpose: worker
        layer: backend
        ai.framework: keras
        ai.backend: tensorflow
        layer: backend
    spec:
      hostname: core
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-core:latest
        imagePullPolicy: Always
        name: core
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/core &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8-splunk.env &&
          export CORE_EXTRA_ARGS="--without-heartbeat --without-gossip" &&
          /opt/antinex/core/run-antinex-core.sh
        env:
        - name: POSTGRES_USER
          value: antinex
        - name: POSTGRES_PASSWORD
          value: antinex
        - name: POSTGRES_DB
          value: webapp
        - name: DEPLOY_CONFIG
          value: splunk
        - name: LOG_NAME
          value: core
        - name: ENV_NAME
          value: k8
        - name: SPLUNK_USER
          value: trex
        - name: SPLUNK_PASSWORD
          value: "123321"
        - name: SPLUNK_INDEX
          value: antinex
        - name: SPLUNK_ADDRESS
          value: splunk-svc:8088
        - name: SPLUNK_API_ADDRESS
          value: splunk-svc:8089
        - name: SPLUNK_TCP_ADDRESS
          value: splunk-tcp-svc:1514
        - name: SPLUNK_HANDLER_NAME
          value: splunk
        - name: SPLUNK_VERIFY
          value: "1"
        - name: SPLUNK_DEBUG
          value: "0"
