apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: splunk-ingress
  namespace: default
spec:
  rules:
  - host: splunkapi.antinex.com
    http:
      paths:
      - path: /
        backend:
          serviceName: splunk-svc
          servicePort: 8089
