apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyter
  annotations:
    description: Jupyter - Web Application for IPython Notebooks Data Science and Analysis
    runtime: python3
  labels:
    app: jupyter
    purpose: analysis
    layer: web
    users: data-scientists
    auth: basic
    messaging: redis
    cache: redis
    pubsub: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
        purpose: analysis
        layer: web
        users: data-scientists
        auth: basic
        messaging: redis
        cache: redis
        pubsub: publisher
    spec:
      hostname: jupyter
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-jupyter:latest
        name: jupyter
        ports:
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 8890
        - containerPort: 6006
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/core/docker/jupyter &&
          export HOME=/opt/antinex/core/docker/jupyter &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8.env &&
          /opt/antinex/core/docker/jupyter/start-container.sh &&
          tail -f /var/log/antinex/jupyter/jupyter.log
        env:
        - name: ANTINEX_USER
          value: trex
        - name: ANTINEX_PASSWORD
          value: "123321"
        - name: JUPYTER_PASS
          value: admin
