apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyter
  annotations:
    description: Jupyter - Web Application for IPython Notebooks Data Science and Analysis
    runtime: python3
  labels:
    app: jupyter
    purpose: analysis
    layer: web
    users: data-scientists
    auth: basic
    messaging: redis
    cache: redis
    pubsub: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
        purpose: analysis
        layer: web
        users: data-scientists
        auth: basic
        messaging: redis
        cache: redis
        pubsub: publisher
    spec:
      hostname: jupyter
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-jupyter:latest
        name: jupyter
        ports:
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 8890
        - containerPort: 6006
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/core/docker/jupyter &&
          export HOME=/opt/antinex/core/docker/jupyter &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8-splunk.env &&
          /opt/antinex/core/docker/jupyter/start-container.sh &&
          tail -f /var/log/antinex/jupyter/jupyter.log
        env:
        - name: ANTINEX_USER
          valueFrom:
            secretKeyRef:
              name: jupyter.api.user
              key: username
        - name: ANTINEX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jupyter.api.user
              key: password
        - name: JUPYTER_PASS
          valueFrom:
            secretKeyRef:
              name: jupyter.user
              key: password
        - name: DEPLOY_CONFIG
          value: splunk
        - name: LOG_NAME
          value: jupyter
        - name: ENV_NAME
          value: k8
        - name: SPLUNK_USER
          valueFrom:
            secretKeyRef:
              name: splunk.user
              key: username
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk.user
              key: password
        - name: SPLUNK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: hec
        - name: SPLUNK_API_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: api
        - name: SPLUNK_TCP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: tcp
        - name: SPLUNK_INDEX
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: index
        - name: SPLUNK_HANDLER_NAME
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: handler
        - name: SPLUNK_VERIFY
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: verify
        - name: SPLUNK_DEBUG
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: debug
