apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  annotations:
    description: AntiNex API Consumers - Celery Django Rest Framework Backend Worker
    runtime: python3
  labels:
    app: worker
    purpose: worker
    layer: backend
    messaging: redis
    cache: redis
    pubsub: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        purpose: worker
        layer: backend
        messaging: redis
        cache: redis
        pubsub: consumer
    spec:
      hostname: worker
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-worker:latest
        imagePullPolicy: Always
        name: worker
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/api &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8.env &&
          export WORKER_EXTRA_ARGS="--without-heartbeat --without-gossip" &&
          /opt/antinex/api/run-worker.sh &&
          tail -f /var/log/antinex/api/worker.log
        env:
        - name: POSTGRES_USER
          value: antinex
        - name: POSTGRES_PASSWORD
          value: antinex
        - name: POSTGRES_DB
          value: webapp
