apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-issuer"
spec:
  tls:
  - hosts:
    - api.antinex.com
    secretName: api.antinex.com-tls
  rules:
  - host: api.antinex.com
    http:
      paths:
      - path: /
        backend:
          serviceName: api-svc
          servicePort: 8010
